{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "virtualnode2.fullname" . }}-{{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
{{- end }}
