{{- if and .Values.rbac.install .Values.virtualdaemonsetControllerManager.enable }}
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
  {{- if and .Values.virtualdaemonsetControllerManager.serviceAccount .Values.virtualdaemonsetControllerManager.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := .Values.virtualdaemonsetControllerManager.serviceAccount.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
  {{- end }}
  name: {{ .Values.virtualdaemonsetControllerManager.serviceAccountName }}
  namespace: {{ .Values.namespace }}
{{- end -}}
