{{- if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.admissionControllerServiceAccountName }}
  namespace: {{ include "virtualnode2.namespace" . }}
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
{{- end }}