{{ if .Values.rbac.install }}
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: ClusterRoleBinding
metadata:
  name: {{ template "virtualnode2.fullname" . }}-{{ .Values.rbac.serviceAccountName }}
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "virtualnode2.fullname" . }}-{{ .Values.rbac.serviceAccountName }}
  namespace: {{ .Values.namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.rbac.roleRef }}
{{ end }}