{{- if .Values.rbac.install }}
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: ClusterRole
metadata:
  name: {{ include "virtualnode2.fullname" . }}-infra
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
rules:
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests"]
    verbs: ["create", "delete", "get", "patch"]
  - apiGroups: ["certificates.k8s.io"]
    resources: ["certificatesigningrequests/nodeclient"]
    verbs: ["create"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: ClusterRoleBinding
metadata:
  name: {{ include "virtualnode2.fullname" . }}-infra
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
subjects:
  {{- include "virtualnode2.infraServiceAccountSubject" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "virtualnode2.fullname" . }}-infra
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: ClusterRoleBinding
metadata:
  name: {{ include "virtualnode2.fullname" . }}-node-proxier
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
subjects:
  {{- include "virtualnode2.infraServiceAccountSubject" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: system:node-proxier
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: Role
metadata:
  name: {{ include "virtualnode2.fullname" . }}-bootstrap
  namespace: kube-system
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
rules:
  - apiGroups: ["apps"]
    resources: ["daemonsets"]
    resourceNames: ["kube-proxy"]
    verbs: ["get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["list"]
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: RoleBinding
metadata:
  name: {{ include "virtualnode2.fullname" . }}-bootstrap
  namespace: kube-system
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
subjects:
  {{- include "virtualnode2.infraServiceAccountSubject" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "virtualnode2.fullname" . }}-bootstrap
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: Role
metadata:
  name: {{ include "virtualnode2.fullname" . }}-events
  namespace: default
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
rules:
  - apiGroups: ["events.k8s.io"]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: RoleBinding
metadata:
  name: {{ include "virtualnode2.fullname" . }}-events
  namespace: default
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
subjects:
  {{- include "virtualnode2.infraServiceAccountSubject" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "virtualnode2.fullname" . }}-events
---
apiVersion: "rbac.authorization.k8s.io/{{ .Values.rbac.apiVersion }}"
kind: Role
metadata:
  name: {{ include "virtualnode2.fullname" . }}-standby-pool-leases
  namespace: {{ include "virtualnode2.namespace" . }}
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "virtualnode2.fullname" . }}-standby-pool-leases
  namespace: {{ include "virtualnode2.namespace" . }}
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
subjects:
  {{- include "virtualnode2.infraServiceAccountSubject" . | nindent 2 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "virtualnode2.fullname" . }}-standby-pool-leases
{{- end }}
