{{ if .Values.rbac.install }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rbac.serviceAccountName }}
  namespace: {{ include "virtualnode2.namespace" . }}
  labels:
    {{- include "virtualnode2.labels" . | nindent 4 }}
  {{- if or (eq .Values.IsWorkloadIdentityEnabled "Enabled") .Values.serviceAccount.annotations }}
  annotations:
    {{- with .Values.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if eq .Values.IsWorkloadIdentityEnabled "Enabled" }}
    azure.workload.identity/client-id: {{ .Values.IdentityClientId | quote }}
    azure.workload.identity/tenant-id: {{ .Values.IdentityTenantId | quote }}
    {{- end }}
  {{- end }}
{{- end }}
